[build-system]
requires = [
  "setuptools >= 40.9.0",
  "wheel",
]
build-backend = "setuptools.build_meta"

[project]
name = "zotify"
version = "0.21.0"
description = "A highly customizable music and podcast downloader"
authors = [
  { name = "Zotify Contributors" },
  { name = "Googolplexed" },
]
requires-python = ">=3.10"
license = "Unlicense"
license-files = ["LICENSE"]
readme = "README.md"
keywords = ["python", "music", "podcast", "downloader"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent"
]
dependencies = [
  "librespot @ git+https://github.com/michaelmwu/librespot-python.git@821c13b41d837283055d1d1054b19c0983877513",
  "ffmpy",
  "music_tag",
  "Pillow",
  "pkce",
  "protobuf==3.20.1",
  "pwinput",
  "tabulate[widechars]",
  "tqdm"
]

[project.scripts]
zotify = "zotify.__main__:main"

[tool.uv]
config-settings = { editable_mode = "compat" }
exclude-newer = "7 days"
